name: Deploy GitHub Pages

on:
  push:
    branches: ["main"]
    
  workflow_dispatch:
    inputs:
      page-root-directory:
        description: Page root directory
        default: './src/'
        type: string

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy Page
    needs: [test]
    env:
      page-root-directory: './src/'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact (Automatic)
        if: (!github.event.inputs.page-root-directory)
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{env.page-root-directory}}

      - name: Upload artifact (Workflow Dispatch)
        if: (github.event.inputs.page-root-directory)
        uses: actions/upload-pages-artifact@v2
        with:
          path: ${{github.event.inputs.page-root-directory}}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
